### ISSUE TITLE
编译后没有生成html是怎么回事？

### ISSUE THREAD

**Issue by ZekerTop** [PancrasL/chinamap-coloring#1]
有按照运行方式来的

**Comment by PancrasL** [comment]
> 有按照运行方式来的

这是由于output文件夹不存在导致的😅，已修复

**Comment by ZekerTop** [comment]
> > 有按照运行方式来的
> 
> 这是由于output文件夹不存在导致的😅，已修复

还是没法

**Comment by PancrasL** [comment]
> > > 有按照运行方式来的
> > 
> > 
> > 这是由于output文件夹不存在导致的😅，已修复
> 
> 还是没法

请提供一下运行环境和错误提示信息

**Comment by ZekerTop** [comment]
> > > > 有按照运行方式来的
> > > 
> > > 
> > > 这是由于output文件夹不存在导致的😅，已修复
> > 
> > 
> > 还是没法
> 
> 请提供一下运行环境和错误提示信息

Python：3.8.5； pip: 21.1.2    没有错误提示信息，运行后没有html文件

**Comment by PancrasL** [comment]
> > > > > 有按照运行方式来的
> > > > 
> > > > 
> > > > 这是由于output文件夹不存在导致的😅，已修复
> > > 
> > > 
> > > 还是没法
> > 
> > 
> > 请提供一下运行环境和错误提示信息
> 
> Python：3.8.5； pip: 21.1.2 没有错误提示信息，运行后没有html文件

1. 确保是在项目目录下执行`python3 view.py 1 0`命令
2. 检查项目目录下的output文件夹，html文件会在该文件夹下生成
3. 如果还是不行请自行修改文件输出路径`view.py`中的`timeline.render(path='output/mapcoloring.html')`，将path替换为自己的路径
